# docker-compose.tunnel.yml

services:
  tunnel:
    build: .
    command: python tunnel.py
    depends_on:
      - web
    environment:
      TUNNEL_SUBDOMAIN: ${TUNNEL_SUBDOMAIN}
      TUNNEL_ENABLED: ${TUNNEL_ENABLED}
      NGR_AUTHTOKEN: ${NGR_AUTHTOKEN}
      APP_PORT: ${APP_PORT}
    env_file:
      - .env.tunnel